steps:
  # Step 1: Install dependencies
  - name: 'node:22'
    entrypoint: 'npm'
    args: ['install']

  # Step 2: Run Sequelize migrations via Cloud SQL Proxy
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    secretEnv: ['DATABASE_URL']
    args:
      - '-c'
      - |
        echo "Downloading Cloud SQL Proxy..."
        curl -o cloud-sql-proxy https://storage.googleapis.com/cloud-sql-connectors/cloud-sql-proxy/v2.14.2/cloud-sql-proxy.linux.amd64
        chmod +x cloud-sql-proxy

        echo "Starting Cloud SQL Proxy..."
        ./cloud-sql-proxy mydeployproject-481214:europe-west2:clientinfo-db --port 5432 &
        PROXY_PID=$$!

        echo "Waiting for proxy to start..."
        sleep 5

        echo "Installing Node.js..."
        apt-get update -qq && apt-get install -y -qq nodejs npm > /dev/null 2>&1

        echo "Running migrations..."
        DATABASE_URL=$$DATABASE_URL npx sequelize-cli db:migrate

        echo "Stopping proxy..."
        kill $$PROXY_PID || true

  # Step 3: Deploy to Google App Engine
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    secretEnv: ['DATABASE_URL']
    args:
      - '-c'
      - |
        gcloud app deploy --quiet --promote --stop-previous-version --set-env-vars DATABASE_URL=$$DATABASE_URL


availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/DATABASE_URL/versions/latest
      env: 'DATABASE_URL'

options:
  logging: CLOUD_LOGGING_ONLY
timeout: '900s'
